[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

evm_version = "shanghai"
fs_permissions = [{access = "read-write", path = "./"}]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config