name: test
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npx hardhat --config hardhat.config.js compile
      - run: npx hardhat --config hardhat.config.5.js compile
      - run: npx hardhat test test_unxswapV3/test*.js
      - run: npx hardhat test test_pmm/test_market_maker.js

